### PR TITLE
Create osc_modif.002

### PR DESCRIPTION
**Pull request by WK-GiHu**
Be aware to the change, delete ALL files in 'tests/out'

### CODE REVIEW

**Comment by jocelynj** [comment]
I don't quite understand - why did you add a new file instead of modifying osc_modif.py before commiting it ?

**Comment by WK-GiHu** [comment]
I'm sorry if I misunderstood that, but 'osc_modif.002' is the modified 'osc_modif.py'.
Is a 'pull request' not the right way to provide access to files? 
Or should I used 'osc_modif.py' as the filename? 

Any suggestions how to continue?

**Comment by jocelynj** [comment]
What you should do is to:
- modify osc_modif.py
- commit the changes on osc_modif.py
- push, and generate a pull request

Then I can easily review the changes, and merge them to my git repository.

**Comment by WK-GiHu** [comment]
Wrong Filename osc_modif.002 used

**Pull request closed without merging**
